LangbaseInc/BaseAI

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json

This PR updates the `baseai/core` & `baseai` package dependencies in the following examples:
- Node.js
- Next.js
- Remis
- Astro

👌 IMPROVE: Update examples dependencies

---

apps/baseai.dev/src/app/providers.tsx

This PR enforces dark mode on home page.

📦 NEW: Force dark mode on home page

---

apps/baseai.dev/content/docs/add/quickstart.mdx
apps/baseai.dev/content/docs/api-reference/get-runner.mdx
apps/baseai.dev/content/docs/api-reference/pipe-run.mdx
apps/baseai.dev/content/docs/guides/using-ollama-embeddings.mdx
apps/baseai.dev/content/docs/memory/quickstart.mdx
apps/baseai.dev/content/docs/tools/quickstart.mdx
apps/baseai.dev/content/learn/learn/configure-tool.mdx
apps/baseai.dev/content/learn/learn/integrate-memory-in-pipe.mdx
apps/baseai.dev/content/learn/learn/integrate-pipe.mdx
apps/baseai.dev/content/learn/learn/integrate-tool-in-pipe.mdx
apps/baseai.dev/content/learn/learn/run-pipe-with-memory.mdx
apps/baseai.dev/content/learn/learn/run-pipe-with-tool.mdx
apps/baseai.dev/src/data/navigation.ts
examples/nodejs/examples/pipe.memory.stream.text.ts
examples/nodejs/examples/pipe.stream.text.ts

This PR updates docs and examples for `pipe.run()` method.

👌 IMPROVE: pipe run for stream and non-stream

---

apps/baseai.dev/content/learn/learn/index.mdx
packages/baseai/src/init/index.ts

- add install dotenv
- add `.env` line to generated `.gitignore` file

Improve docs

---

packages/baseai/src/dev/llms/call-fireworks.ts

This PR fixes a bug with fireworks models in BaseAI local.

🐛 FIX: Fireworks models

---

packages/baseai/src/data/models.ts
packages/baseai/src/dev/data/models.ts
packages/baseai/src/dev/providers/google/chatComplete.ts
packages/baseai/types/model.ts
packages/core/src/data/models.ts
packages/core/types/model.ts

This PR adds the new Gemini Flash 8B model in BaseAI.

📦 NEW: gemini-flash-8b

---

examples/nodejs/baseai/memory/chat-with-repo/index.ts
examples/nodejs/baseai/pipes/chat-with-repo.ts
examples/nodejs/examples/pipe.git-memory.stream.text.ts
packages/baseai/package.json
packages/baseai/src/deploy/document.ts
packages/baseai/src/deploy/index.ts
packages/baseai/src/dev/utils/thread/get-system-prompt.ts
packages/baseai/src/index.ts
packages/baseai/src/memory/create.ts
packages/baseai/src/utils/init.ts
packages/baseai/src/utils/memory/git-sync/get-changed-files-between-commits.ts
packages/baseai/src/utils/memory/git-sync/handle-git-sync-memories.ts
packages/baseai/src/utils/memory/git-sync/save-deployed-commit-in-config.ts
packages/baseai/src/utils/memory/lib.ts
packages/baseai/src/utils/memory/load-memory-config.ts
packages/baseai/src/utils/memory/load-memory-files.ts
packages/baseai/types/memory.ts
packages/core/types/memory.ts
pnpm-lock.yaml

This is a draft PR for implementing auto-synced memories with git repos.

📦 NEW: Synced memory with git

---

apps/baseai.dev/content/docs/deployment/memory.mdx
apps/baseai.dev/content/docs/guides/memory-from-git.mdx
apps/baseai.dev/src/data/navigation.ts

Add docs for git synced memory and single memory deploy

📖 DOC: Git Synced Memory & Single Memory Deploy 

---

packages/baseai/src/deploy/index.ts
packages/core/types/config.ts

This PR fixes memory deploy by adding a missing optional check for the memory config. It also adds a missing config type.

🐛 FIX: Memory deploy

---

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json
pnpm-lock.yaml

This PR updates examples' BaseAI packages to new released version of BaseAI.

📦 NEW: Update examples baseai packages

---

CONTRIBUTING.md
packages/baseai/src/deploy/index.ts
packages/baseai/src/memory/create.ts
packages/baseai/src/utils/memory/git-sync/handle-git-sync-memories.ts

This PR makes improvements to:
- deploy all command
- memory create command
- how we detect uncommitted changes in git synced memories

👌 IMPROVE: Deployment and memory workflows

---

packages/baseai/src/memory/embed.ts

Check was wrong, fixed the embeddings check.

🐛 FIX: Local embeddings generation

---

apps/baseai.dev/content/docs/docs/supported-models-and-providers.mdx

This PR updates models in docs.

📦 NEW: update docs

---

packages/baseai/src/data/models.ts
packages/baseai/src/dev/data/models.ts
packages/baseai/src/dev/llms/call-openai.ts
packages/baseai/src/dev/utils/add-tools-to-params.ts
packages/baseai/src/dev/utils/has-tool-support.ts

This PR refactors tool call code in BaseAI. We now have a central point that checks if a model supports tool. If it does, it adds tools to the model params.

👌 IMPROVE: Tool call code refactor

---

packages/baseai/src/dev/llms/call-anthropic.ts
packages/baseai/src/dev/providers/anthropic/chatComplete.ts
packages/baseai/types/providers.ts

This PR adds tool call support to all models provided by Anthropic.

📦 NEW: Anthropic tool call support

---

packages/baseai/src/dev/llms/call-google.ts
packages/baseai/src/dev/providers/google/chatComplete.ts
packages/baseai/src/dev/providers/utils.ts
packages/baseai/types/pipe.ts
packages/baseai/types/providers.ts

This PR adds tool call support to all models provided by Google.

📦 NEW: Google tool call support

---

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json
pnpm-lock.yaml

This PR bumps packages versions to `0.9.13`

👌 IMPROVE: Bump packages versions

---

apps/baseai.dev/content/docs/docs/supported-models-and-providers.mdx
packages/baseai/src/data/models.ts
packages/baseai/src/dev/data/models.ts
packages/baseai/types/model.ts
packages/core/src/data/models.ts
packages/core/types/model.ts

Adds claude-3.5-sonnet-latest which currently points to `20241022` version.

📦 NEW: Add claude-3.5-sonnet-latest

---

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json
pnpm-lock.yaml

This PR bumps packages to the new 0.9.17 version.

📦 NEW: Bump packages to 0.9.17

---

apps/baseai.dev/content/learn/learn/index.mdx

fixed project setup on directory creation and navigating before initiating the `npm`

📖 DOC: Update learn guide

---

.changeset/config.json

This PR fixes changeset by removing the testing package which is no longer used.

🐛 FIX: changeset

---

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json
pnpm-lock.yaml

📦 NEW: Bump packages

---

apps/baseai.dev/src/components/home/hero.tsx

This PR fixes LP mobile UI of BaseAI.dev.

👌 IMPROVE: Landing page mobile UI

---

apps/baseai.dev/src/components/home/hero.tsx
apps/baseai.dev/src/components/home/webgl.tsx
apps/baseai.dev/src/styles/global.css

- Double logo on Docs page fixed
- Fixed the content spacing issue on homepage
- WebGL code cleanup

🐛 FIX: Logo Overlapping and Content Spacing Fix

---

packages/baseai/src/dev/providers/anthropic/chatComplete.ts

This PR fixes Anthropic response streaming by adding missing "assistant" role.

🐛 FIX: Anthropic streaming

---

examples/nextjs/app/api/langbase/pipes/run-tool-stream/route.ts
examples/nextjs/app/demo/tool-calling-stream/page.tsx
examples/nextjs/app/page.tsx
examples/nextjs/baseai/pipes/pipe-with-tool-stream.ts
examples/nextjs/baseai/pipes/pipe-with-tool.ts
examples/nextjs/components/pipe-run-with-tool-stream.tsx
packages/core/src/helpers/stream.ts
packages/core/src/pipes/pipes.ts

This PR adds:
- Stream support in tools calls for OpenAI, TogetherAI, Google.
Previously, we disabled the streaming altogether for a pipe if it contained any tool.

📦 NEW: Stream support in tool call

---

packages/baseai/src/data/models.ts
packages/baseai/src/dev/data/models.ts
packages/baseai/types/model.ts
packages/core/src/data/models.ts
packages/core/src/pipes/pipes.ts
packages/core/types/model.ts

This PR adds support for Claude 3.5 Haiku in BaseAI.

📦 NEW: Claude 3.5 Haiku

---

packages/baseai/src/build/index.ts

This PR fixes broken build path for pipes and tools in Windows.

🐛 FIX: Pipes and tools build paths

---

packages/core/src/pipes/pipes.ts
packages/core/src/utils/is-prod.ts
packages/core/src/utils/local-server-running.ts

This PR adds the ability to request production AI agent pipe by setting `prod` flag to true.

📦 NEW: Request production AI agent pipe

---

examples/nextjs/app/api/langbase/pipes/run-stream/route.ts
examples/nextjs/app/api/langbase/pipes/run/route.ts
examples/nextjs/components/pipe-run.tsx
packages/core/src/react/use-pipe.ts

This PR improves error handling in `usePipe` by passing the actual error object from the API to the error object in `usePipe`.

👌 IMPROVE: Error handling in usePipe

---

examples/astro/package.json
examples/nextjs/package.json
examples/nodejs/package.json
examples/remix/package.json
pnpm-lock.yaml

This PR bumps examples to new 0.9.32 version.

📦 NEW: Bump to 0.9.32

---

apps/baseai.dev/content/docs/guides/memory-from-git.mdx

Updated docs related to new config for git tracked memory.

👌 IMPROVE: Docs for updated git config

---

packages/baseai/src/deploy/index.ts
packages/baseai/src/utils/memory/handle-old-memory-config.ts
packages/baseai/src/utils/memory/load-memory-config.ts

This PR adds graceful handling of old memory config format during deployment and embed functions.

📦 NEW: Handle old format memory config

---

packages/core/src/pipes/pipes.ts

This PR adds support for pipe API key in pipe.run().

📦 NEW: Pipe API key support

---

packages/baseai/src/data/models.ts
packages/baseai/src/dev/data/models.ts
packages/baseai/types/model.ts
packages/core/src/data/models.ts
packages/core/types/model.ts

This PR adds `meta-llama/Llama-3.3-70B-Instruct-Turbo` model w/ Together, Groq, and Fireworks AI.

📦 NEW: meta-llama/Llama-3.3-70B-Instruct-Turbo model

---

packages/baseai/src/dev/utils/moderate.ts

This PR fixes the moderation model issue (#151) by using `omni-moderation-latest` as the moderation model.

🐛 FIX: Moderation model 
