examples/nodejs/examples/pipe.generate.text.ts
examples/nodejs/examples/pipe.memory.stream.text.ts
examples/nodejs/examples/pipe.run.stream.loop.ts
examples/nodejs/examples/pipe.run.stream.ts
examples/nodejs/examples/pipe.run.ts
examples/nodejs/examples/pipe.stream.text.ts

This PR fixes Node.js example by importing `dotenv` top of TS files.

🐛 FIX: Import `dotenv` in Node.js example

---

apps/baseai.dev/src/app/learn/[section]/layout.tsx

In learn, we are importing SEO details from the wrong file. This PR fixes it and uses the correct `learn.json` file.

🐛 FIX: Learn SEO

---

packages/core/src/common/errors.ts

This PR improves API connection error handling by displaying a warning in the terminal asking user to check if the BaseAI dev server is running.

👌 IMPROVE: Ask user to check if dev server is running

---

packages/baseai/src/dev/providers/google/chatComplete.ts

This PR fixes an edge case error of Google Gemini models where the parts object is undefined in response.

🐛 FIX: Google error

---

apps/baseai.dev/content/docs/deployment/deploy.mdx
apps/baseai.dev/content/docs/deployment/document.mdx
apps/baseai.dev/content/docs/memory/create.mdx
apps/baseai.dev/content/docs/memory/embed-document.mdx
apps/baseai.dev/content/docs/memory/embed.mdx
apps/baseai.dev/content/docs/memory/list.mdx
apps/baseai.dev/content/docs/memory/retrieve.mdx
apps/baseai.dev/src/data/navigation.ts
examples/nodejs/.gitignore
packages/baseai/package.json
packages/baseai/src/build/index.ts
packages/baseai/src/deploy/document.ts
packages/baseai/src/deploy/index.ts
packages/baseai/src/index.ts
packages/baseai/src/memory/embed-doc.ts
packages/baseai/src/utils/init.ts
packages/baseai/src/utils/memory/check-memory-doc-exists.ts
packages/baseai/src/utils/memory/compare-docs-list.ts
packages/baseai/src/utils/memory/lib.ts
packages/baseai/src/utils/memory/load-memory-files.ts
packages/baseai/types/memory.ts
pnpm-lock.yaml

This PR takes care of the following:
- Deploy single doc to a memory on langbase using 
```sh
npx baseai deploy -m <memory-name> -d <doc-name>
```
- If doc doesn't exist in prod, we upload the doc in memory
- If doc exists in prod, we exit the process and ask user to run the same command with `-o` overwrite flag
- Add deploy a doc to memory [docs](https://saad-deploy-documents.baseai-291.pages.dev/docs/deployment/document)

📦 NEW: Deploy doc to memory

---

packages/baseai/src/memory/create.ts

Fixes default value of fileExtensions to `['*']` and dirToTrack to `.`, otherwise config validation fails.

🐛 FIX: Default config for non-git-sync memory

---

packages/baseai/src/deploy/index.ts
packages/baseai/src/memory/embed.ts
packages/baseai/src/utils/memory/generate-embeddings.ts
packages/baseai/src/utils/memory/git-sync/get-changed-files-between-commits.ts
packages/baseai/src/utils/memory/git-sync/handle-git-sync-memories.ts
packages/baseai/src/utils/memory/git-sync/save-embedded-commit-in-config.ts
packages/baseai/src/utils/memory/load-memory-config.ts
packages/baseai/types/memory.ts
packages/core/types/memory.ts

- Adds support for local embed in git-sync memory 
- Moves update hash function to after deployment completes

📦 NEW: Add embed support for git-sync memory

---

packages/baseai/src/dev/llms/call-together.ts

This PR adds tool call support to the following TogetherAI models:
- meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo
- meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo
- meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
- mistralai/Mistral-7B-Instruct-v0.1
- mistralai/Mixtral-8x7B-Instruct-v0.1

📦 NEW: TogetherAI tool call support

---

packages/core/src/pipes/pipes.ts
packages/core/src/react/use-pipe.ts
packages/core/types/pipes.ts

We currently have different `Message` types inside `core/src/pipes/pipes.ts` and `core/types/pipes.ts`. This leads to issue with `usePipe` hook. 
The hook internally uses `Message` type from `core/types/pipes.ts`. Whereas the available exported `Message` type from the package is from `core/src/pipes/pipes.ts` (type getting overwritten here). This leads to type mismatch when user passes `messages` from usePipe down a component via props in a TS file.
This PR unifies different `Message` types and uses it inside `usePipe` hook so the correct type is exported from the package.

🐛 FIX: Overwrite message types

---

packages/baseai/src/utils/memory/git-sync/handle-git-sync-memories.ts
packages/baseai/src/utils/memory/load-memory-files.ts

This PR handles git ignored files in git repo memories.
Previously, deploying the repo with root path selected included git ignored files like the `node_modules` folder. This PR fixes it and properly ignores those files.

📦 NEW: Handle gitignored files in git repo memory

---

packages/baseai/src/utils/memory/lib.ts

If a pipe has a memory, the messages array gets reversed that results in first message being used as the latest message for LLM. This PR fixes it.

🐛 FIX: Message order when memory attached

---

packages/core/src/common/request.ts
packages/core/src/helpers/stream.ts
packages/core/src/react/use-pipe.ts

This PR takes care of the following:
- Export `setInput` from `usePipe` to directly set the state
- Export `handleStreamResponse` to process LB prod API stream

📦 NEW: Export helper functions

---

packages/baseai/src/deploy/index.ts

This PR fixes the following where spinner does not stop on BaseAI deploy that leads to CLI not exiting correctly.

🐛 FIX: BaseAI deploy spinner not stopped

---

packages/core/src/pipes/pipes.ts

This PR allows user to intercept tool call instead of executing it by default.

📦 NEW: `runTools` run options param in pipe.run()

---

packages/core/src/react/use-pipe.ts

This PR adds a new `setThreadId` function in usePipe hook to set custom thread id.

📦 NEW: `setThreadId` function in usePipe

---

packages/core/src/common/request.ts

This PR dynamically timeouts request if there `this.config.timeout` exists. This will prevent timing out request when response takes longer than 30s.

📦 NEW: Remove default request timeout

---

packages/baseai/src/memory/create.ts
packages/baseai/src/pipe/index.ts
packages/baseai/src/tool/index.ts

BaseAI CLI breaks when user provides a special character in pipe, memory or tool description when creating any of them. This PR fixes it.

🐛 FIX: Handle special characters in description

---

packages/core/src/react/use-pipe.ts

This PR adds empty submit functionality, which let's users send the request with empty/no message. 
This is handled by a `allowEmptySubmit` flag in RunOptions which is false by default. 
Example usage with usePipe: 
```ts
const options = {body, headers, allowEmptySubmit: true}
handleSubmit(e, options);
```

📦 NEW: Allow empty submit

---

packages/baseai/src/build/index.ts

This PR fixes execAsync breaking paths for Windows.

🐛 FIX: execAsync windows path

---

packages/core/src/pipes/pipes.ts

This PR adds params in `pipe.run()` so it can be used in Langbase SDK.

📦 NEW: Params for pipe.run() sdk support

---

examples/nodejs/baseai/memory/ai-agent-memory/index.ts
packages/baseai/src/deploy/index.ts
packages/baseai/src/utils/memory/load-memory-files.ts
packages/baseai/types/memory.ts
packages/core/types/memory.ts

This PR adds the ability to dynamically set document metadata using memory config.
```ts
import {MemoryI} from '@baseai/core';
const memoryAiAgentMemory = (): MemoryI => ({
name: 'ai-agent-memory',
description: 'My list of docs as memory for an AI agent pipe',
git: {
enabled: true,
include: ['**/*'],
gitignore: true,
deployedAt: '',
embeddedAt: '',
},
document: {
meta: doc => {
return {
name: doc.name,
path: doc.path,
};
},
},
});
export default memoryAiAgentMemory;
```

📦 NEW: Dynamically set document metadata

---

packages/baseai/package.json
packages/baseai/src/add/index.ts
packages/baseai/src/auth/index.ts
packages/baseai/src/deploy/document.ts
packages/baseai/src/deploy/index.ts
packages/baseai/src/utils/retrieve-credentials.ts
pnpm-lock.yaml

This PR includes the following changes:
- `npx baseai auth` now only saves/updates API key in `.env` file
- If key exists already then we ask user if they want to overwrite.
- `npx baseai deploy` use Langbase API key from `.env` file instead of global config

📦 NEW: Use Langbase API key from .env file to deploy

---

examples/nextjs/app/api/langbase/pipes/run-tool-stream/route.ts
packages/baseai/src/dev/llms/call-anthropic.ts
packages/baseai/src/dev/llms/call-google.ts
packages/baseai/src/dev/llms/call-llm.ts
packages/baseai/src/dev/llms/call-openai.ts
packages/baseai/src/dev/llms/call-together.ts
packages/baseai/src/dev/llms/call-xai.ts
packages/baseai/src/dev/routes/v1/pipes/run.ts
packages/baseai/src/dev/utils/add-tools-to-params.ts
packages/baseai/types/tools.ts
packages/core/src/helpers/stream.ts
packages/core/src/pipes/pipes.ts
packages/core/types/pipes.ts

This PR includes change to support `tools` in `pipe.run()`. Users can now send tool definition to run endpoint. 
1. If no tools exists in pipe, `tools` in pipe will be passed to the LLM.
2. If user sends tools in request params and tools also exists in pipe, run options tools are priortized.

📦 NEW: tools support in pipe.run() endpoint
